FROM scratch

LABEL org.opencontainers.image.source="https://github.com/gbraad-dotfiles/freebsd"
LABEL org.opencontainers.image.description="Standalone FreeBSD Test Cloud Image Container"

ADD ./output-freebsd/packer-freebsd /disk.qcow2

